### PR TITLE
Update year 2024

### PR DESCRIPTION
**Pull request by javiarrobas**

### CODE REVIEW

**Review by mdhanna — CHANGES_REQUESTED** [review]
Thank you for reformatting! Would you be able to clear the cell outputs from the exercises and instead show what the outputs should be under the solution? Otherwise this is good to go!

**Comment by javiarrobas** [comment]
@mdhanna thanks for reviewing and providing feedback! sure, I can clear the cell outputs in the exercises. showing the actual output in the solutions would require copying the cells from the exercises with a lot of code duplicities which can be confusing, so I'm guessing then you expect something like a small sentence describing the outcome in the Solution as in your example [here](https://colab.research.google.com/drive/1pJacEOyHAYqOOBtyJeVfsqf6Yr8pSuYc#scrollTo=uMWZdS7TagsY) right? 
ps: in the meantime I found out that the outline was not reflecting the actual titles so I made a small update there too.

**Comment by mdhanna** [comment]
Yes a sentence should work! My concern with showing the output from the exercise cell is that it will get overwritten when the student enters their own code and tries to run it. As long as we capture what the expected output should be somewhere in the solution, that will be fine.

**Comment by javiarrobas** [comment]
Hopefully it's fine now :)
Please let me know otherwise @mdhanna!

**Review by mdhanna — APPROVED** [review]
Thanks Javier!

**Pull request merged**
